// generated by args/argparser.c
// compiled at 2021-02-12 12:01:59.119869
// created by llamaking136

// Copyright 2021 llamaking136

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

//     http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


#if !defined(ARGPARSER_H)
#define ARGPARSER_H

#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include "../main/version.h"

int usage();
int helppage();
int printversion();

int parseargs(int argc, char** argv);

#endif // ARGPARSER_H
