// generated by lib/array.h
// compiled at 2021-02-11 21:12:51.356587
// created by llamaking136

// Copyright 2021 llamaking136

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

//     http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


#if !defined(ARRAY_H)
#define ARRAY_H

#include "../parser/token.h"
#include <stdio.h>

typedef struct TokenArray {
    Token* array;
    size_t used;
    size_t size;
} TokenArray;

void initArray(TokenArray* t, size_t initalSize);
void insertArray(TokenArray* t, Token element);
void freeArray(TokenArray* t);

#endif // ARRAY_H
