// auto-generated by makeNewFile
// compiled at 2021-02-11 20:59:09.859053
// created by llamaking136

// Copyright 2021 llamaking136

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

//     http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "main.h"

int main(int argc, char** argv) {
    parseargs(argc, argv);
    char* data = fileread(argv[1]);
    // TokenArray tokens = Tokenize(fileread(argv[1]));
    // printArray(&tokens);
    return 0;
}
