// generated by makeNewFile
// compiled at 2021-02-11 21:01:11.254696
// created by llamaking136

// Copyright 2021 llamaking136

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

//     http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


#if !defined(MAIN_H)
#define MAIN_H

#if defined(WIN32)
# error cthing does not support windows (yet)
#endif // WIN32

#include <array.h>
#include "../parser/parser.h"
#include "../args/argparser.h"
#include "../parser/fileread.h"

int main(int argc, char** argv);

#endif // MAIN_H
