// generated by makeNewFile
// compiled at 2021-02-11 21:01:11.254696
// created by llamaking136

// Copyright 2021 llamaking136

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

//     http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


#if !defined(TOKENIZER_H)
#define TOKENIZER_H

#define INT_MAX_SIZE 1024

#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdint.h>

#include <array.h>
#include "token.h"
#include "fileread.h"

extern const char* DIGITS;
extern const char* NAMES;

TokenArray Tokenize(char*);

Token get_number(char*, uint32_t*, uint32_t*, char*);

#endif // TOKENIZER_H
